== Use Case 3 - Camel Route publishing the messages into a queue and handling the DLQ messages

The purpose of this use case is to extend/revisit the use case 1 to publish the JSON messages into different queues instead of the folders outbox and error.
For the erroneous messages, you will replace the DLQ folder with a DLQ queue and will develop a strategy to update/correct the erroneous messages
and re inject these messages into the normal flow. A redelivery policy must be put in place to avoid that the client, through the connection factory
, tries to redeliver the erroneous message.

A notification/alert mechanism must be developed to send a message to a topic containing the error code and error message. To be notified that there is an error,
an interception strategy must be defined to check if there is an IllegalArgumentException generated. If this is case, an error code and the exception message will
be added to the message that you will publish on a topic.
A client is connected to this topic in order to be informed about the error reported when a faulty exception is thrown. The erroneous message and the message code
received will be saved into an error table. Each record created will be managed with a status (ERROR, FIXED, CLOSE).
According to the strategy that you have developed to correct the message, you will next resend/republish it to the queue consuming
the input messages in order to process it if the status value is equal to FIXED. The messages consuled from the database will have finally their status updated to the value CLOSE.

.Goals
* Combine the Routing and Integration technology with a messaging platform
* Develop a project able to use locally Apache ActiveMQ or JBoss A-MQ to publish the messages into different queues
* Use the DLQ pattern supported by Apache ActiveMQ / JBoss A-MQ
* Implement a redelivery strategy with Apache ActiveMQ / JBoss A-MQ to disable th redelivery
* Notify the durable subscriber client using a topic that erroneous messages have been produced
* Report the error (code and message) within the usecase database (table T_ERROR)
* Report also the error on the console using Log4j with the logging level "DEBUG" and the logger name "org.fuse.usecase"
* Use the Camel SQL component to INSERT the record within the DB and listen to corrected messages from the table T_ERROR

=== Related Links
Related Links about the topics included in this Use Case:

* link:http://camel.apache.org/intercept.html[Camel Intercept]

* link:http://activemq.apache.org/message-redelivery-and-dlq-handling.html[Message Redelivery and DLQ Handling]

* link:http://camel.apache.org/sql-component.html[Camel SQL Component]
